org.gradle.caching=true
group=io.ballerina.lib

# This is a dummy value as repo contains multiple packages
version=1.0.0-SNAPSHOT
api_inforecord_process_srvVersion=1.0.0-SNAPSHOT

ballerinaGradlePluginVersion=4.0.1
downloadPluginVersion=5.4.0
releasePluginVersion=3.1.0

ballerinaLangVersion=2201.9.0
